import { useEffect, useState } from "react";
import Head from "next/head";

import { gql } from "@apollo/client";
import client from "../apolloClient";

export default function Home({ blogPosts }) {
  return (
    <div>
      <Head>
        <title>Blog Initial Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>List of articles</h1>
        <ul>
          {blogPosts?.map((post) => {
            return (
              <li key={post.id}>
                <a href={`/artigos/${post.slug}`}>{post.title}</a>
              </li>
            );
          })}
        </ul>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query MyQuery {
        blogPosts {
          id
          title
          stage
          slug
        }
      }
    `,
  });

  return {
    props: {
      blogPosts: data.blogPosts,
    },
    revalidate: 10,
  };
}
